// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxKIjK0XZHbvK-f2o5_UZBA1vUgr4CrJ8',
    appId: '1:808216381041:web:c905f2c299e4fc255b7dd0',
    messagingSenderId: '808216381041',
    projectId: 'atlas-paragliding',
    authDomain: 'atlas-paragliding.firebaseapp.com',
    storageBucket: 'atlas-paragliding.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHs_nb0LsoA_fBbBniZ4COoa0PtNFXubE',
    appId: '1:808216381041:android:79cabc2a2b949ec75b7dd0',
    messagingSenderId: '808216381041',
    projectId: 'atlas-paragliding',
    storageBucket: 'atlas-paragliding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlzz53KfY7ux4p8DXgrIRga12MCi4OUfY',
    appId: '1:808216381041:ios:515870c5ff83584d5b7dd0',
    messagingSenderId: '808216381041',
    projectId: 'atlas-paragliding',
    storageBucket: 'atlas-paragliding.firebasestorage.app',
    iosBundleId: 'com.example.atlasParagliding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlzz53KfY7ux4p8DXgrIRga12MCi4OUfY',
    appId: '1:808216381041:ios:515870c5ff83584d5b7dd0',
    messagingSenderId: '808216381041',
    projectId: 'atlas-paragliding',
    storageBucket: 'atlas-paragliding.firebasestorage.app',
    iosBundleId: 'com.example.atlasParagliding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxKIjK0XZHbvK-f2o5_UZBA1vUgr4CrJ8',
    appId: '1:808216381041:web:90b17099a5f608145b7dd0',
    messagingSenderId: '808216381041',
    projectId: 'atlas-paragliding',
    authDomain: 'atlas-paragliding.firebaseapp.com',
    storageBucket: 'atlas-paragliding.firebasestorage.app',
  );

}